version: '3.4'

networks:
    mynetwork:


services:
    api:
        image: quest_room_srv_api:latest
        build:
            context: ./questRoomSrv_api/
            dockerfile: Dockerfile
        restart: always
        container_name: questRoomSrv_api
        ports:
          # - "${API_PORT}:${API_PORT}"
          - "${API_PORT}:80"
        env_file:
          - '.env'
        volumes:
          - ./questRoomSrv_api:/usr/src/questRoomSrv_api
        depends_on:
          - db
        networks:
          - mynetwork


    db:
      image: postgres
      container_name: questRoomSrv_db
      restart: always
      env_file:
        - '.env'
      environment:
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_HOST: "${POSTGRES_HOST}"
      expose:
        - "${POSTGRES_PORT}"
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      networks:
        - mynetwork


  # Mosquitto broker for mqtt protocol connection
    mosquitto:
      build:
          context: ./mosquitto/
          dockerfile: Dockerfile
      restart: always
      container_name: mosquitto
      expose:
        - "${BROKER_PORT}"
        - 9001
      env_file:
        - '.env'
      ports:
        - "${BROKER_PORT}:${BROKER_PORT}"
        - 9001:9001
      depends_on:
        - api
      networks:
        - mynetwork


    mqtt_master:
      image: mqtt_master:latest
      build:
          context: ./mqtt_master/
          dockerfile: Dockerfile
      restart: always
      container_name: mqtt_master
      env_file:
        - '.env'
      volumes:
        - ./mqtt_master:/usr/src/mqtt_master
      depends_on:
        - mosquitto
      networks:
        - mynetwork
