"""empty message

Revision ID: 5f780af7f42e
Revises: edfd7f1a47cc
Create Date: 2020-11-23 10:49:31.373252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f780af7f42e'
down_revision = 'edfd7f1a47cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('quest_index', sa.Integer(), nullable=True))
    op.drop_constraint('quests_index_key', 'quests', type_='unique')
    op.create_unique_constraint(None, 'quests', ['quest_index'])
    op.drop_column('quests', 'index')
    op.drop_column('quests', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quests', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quests', type_='unique')
    op.create_unique_constraint('quests_index_key', 'quests', ['index'])
    op.drop_column('quests', 'quest_index')
    # ### end Alembic commands ###
